### PR TITLE
Nf 368 surface processed time

### PR DESCRIPTION
**Pull request by rorticus0502**

### CODE REVIEW

**Comment by SteveSugden** [comment]
We'll need to convert that date from String to object (LocalDateTime?) at some point.  Not sure where the best place to do that is.  Perhaps it is in the `EISCreateCaseResponse` model (i.e. when we first receive it).   Although that might mean messing around with Json datatime formats in multiple places.

**Comment by rorticus0502** [comment]
> We'll need to convert that date from String to object (LocalDateTime?) at some point. Not sure where the best place to do that is. Perhaps it is in the `EISCreateCaseResponse` model (i.e. when we first receive it). Although that might mean messing around with Json datatime formats in multiple places.

Yep, I mulled this.
My thinking was;
If I parse it now, and it is successful, then great, I can pass it confidently through to our front end, where it will need to be parsed again.
If I parse it now and it fails, cos it is not valid, what should I do? I could use NOW as a timestamp but that would be making up data. I could omit it. I definitely dont want to throw an exception.
On balance I thought it best to pass whatever EIS gives us to the front end where we will use it.
If our front end cannot parse it/we decides what to do.

**Comment by SteveSugden** [comment]
I wouldn't worry too much about the parsing failing.  If it fails then we're getting an invalid date/time from EIS and we have a problem (where ever the parsing is done).   I'll see if I can have a fiddle over the weekend to illustrate the options.

**Comment by SteveSugden** [comment]
Good news.   LocalDateTime can be converted from Json without any extra faffing around.   Simple change to this
```
case class EISCreateCaseSuccess(CaseID: String, ProcessingDate: LocalDateTime, Status: String, StatusText: String)
    extends EISCreateCaseResponse
```
and you can treat the value as a data/time

`println(s"EIS RESPONSE: $success")`

`EIS RESPONSE: EISCreateCaseSuccess(NIDKUGRG5ODTEBEXIGBXGD,2021-04-01T18:17:42.128,OK,Case created)`

**Comment by rorticus0502** [comment]
Thanks Steve.

I have made the change to convert the processingDate to LocalDateTime upon receiving it from EIS 
Ready for re-review.

**Review by SteveSugden — APPROVED** [review]

**Pull request merged**
